#!/usr/bin/bash

declare GIT_ROOT=`git rev-parse --show-toplevel | head -1`
declare HOOK_NAME=`basename $0`
declare LOCAL_HOOK="${GIT_ROOT}/.git/hooks/${HOOK_NAME}"
declare SCRIPT_DIR=`realpath $(dirname $0)`
declare IGNORE_GLOBAL_HOOKS=$(dirname ${SCRIPT_DIR})/IGNORE_GLOBAL_HOOKS

if [[ -e $LOCAL_HOOK ]]; then
    $LOCAL_HOOK
fi

if [[ -f "$IGNORE_GLOBAL_HOOKS" ]]; then
    if cat $IGNORE_GLOBAL_HOOKS | grep -q $GIT_ROOT; then
        exit 0
    fi
fi
